project_identifier: poedit
base_url: http://api.crowdin.net
base_path: .
preserve_hierarchy: false

files:
  -
    source: /locales/poedit.pot
    translation: /locales/%locale_with_underscore%.po
    languages_mapping:
      locale_with_underscore:
        af: af
        am: am
        an: an
        ar: ar
        ast: ast
        az: az
        be: be
        bg: bg
        bn: bn
        bs: bs
        ca: ca
        ckb: ckb
        co: co
        cs: cs
        da: da
        de: de
        el: el
        eo: eo
        et: et
        eu: eu
        fa: fa
        fi: fi
        fr: fr
        gl: gl
        he: he
        hi: hi
        hr: hr
        hu: hu
        id: id
        is: is
        it: it
        ja: ja
        ka: ka
        kk: kk
        ko: ko
        ku: ku
        ky: ky
        lt: lt
        lv: lv
        mk: mk
        mn: mn
        mr: mr
        ms: ms
        nb: nb
        nl: nl
        pl: pl
        ro: ro
        ru: ru
        sk: sk
        sl: sl
        sq: sq
        sr: sr
        ta: ta
        tg: tg
        th: th
        tr: tr
        ug: ug
        uk: uk
        uz: uz
        vi: vi
        wa: wa
        br-FR: br
        es-ES: es
        fur-IT: fur
        ga-IE: ga
        ne-NP: ne
        nn-NO: nn
        pa-IN: pa
        pt-PT: pt
        sv-SE: sv
        tt-RU: tt
        ur-PK: ur
        val-ES: ca@valencia
        zh-CN: zh_CN
        zh-TW: zh_TW
  -
    source: /macosx/en.lproj/InfoPlist.strings
    translation: /macosx/%osx_code%/InfoPlist.strings
    languages_mapping:
      osx_code:
        es-ES: es.lproj
        pt-PT: pt.lproj
        sv-SE: sv.lproj
  -
    source: /macosx/en.lproj/MoveApplication.strings
    translation: /macosx/%osx_code%/MoveApplication.strings
    languages_mapping:
      osx_code:
        es-ES: es.lproj
        pt-PT: pt.lproj
        sv-SE: sv.lproj

